/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as HelloImport } from './routes/hello'
import { Route as IndexImport } from './routes/index'
import { Route as Hello2IndexImport } from './routes/hello2/index'

// Create/Update Routes

const HelloRoute = HelloImport.update({
  path: '/hello',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const Hello2IndexRoute = Hello2IndexImport.update({
  path: '/hello2/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/hello': {
      id: '/hello'
      path: '/hello'
      fullPath: '/hello'
      preLoaderRoute: typeof HelloImport
      parentRoute: typeof rootRoute
    }
    '/hello2/': {
      id: '/hello2/'
      path: '/hello2'
      fullPath: '/hello2'
      preLoaderRoute: typeof Hello2IndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hello': typeof HelloRoute
  '/hello2': typeof Hello2IndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hello': typeof HelloRoute
  '/hello2': typeof Hello2IndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/hello': typeof HelloRoute
  '/hello2/': typeof Hello2IndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hello' | '/hello2'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hello' | '/hello2'
  id: '__root__' | '/' | '/hello' | '/hello2/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HelloRoute: typeof HelloRoute
  Hello2IndexRoute: typeof Hello2IndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HelloRoute: HelloRoute,
  Hello2IndexRoute: Hello2IndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/hello",
        "/hello2/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/hello": {
      "filePath": "hello.tsx"
    },
    "/hello2/": {
      "filePath": "hello2/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
